/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembersRouteImport } from './routes/members'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoErrorBoundaryRouteImport } from './routes/demo/error-boundary'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DemoAuthRouteImport } from './routes/demo/auth'

const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoErrorBoundaryRoute = DemoErrorBoundaryRouteImport.update({
  id: '/demo/error-boundary',
  path: '/demo/error-boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAuthRoute = DemoAuthRouteImport.update({
  id: '/demo/auth',
  path: '/demo/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/members': typeof MembersRoute
  '/demo/auth': typeof DemoAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/error-boundary': typeof DemoErrorBoundaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/members': typeof MembersRoute
  '/demo/auth': typeof DemoAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/error-boundary': typeof DemoErrorBoundaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/members': typeof MembersRoute
  '/demo/auth': typeof DemoAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/error-boundary': typeof DemoErrorBoundaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/members'
    | '/demo/auth'
    | '/demo/convex'
    | '/demo/error-boundary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/members' | '/demo/auth' | '/demo/convex' | '/demo/error-boundary'
  id:
    | '__root__'
    | '/'
    | '/members'
    | '/demo/auth'
    | '/demo/convex'
    | '/demo/error-boundary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MembersRoute: typeof MembersRoute
  DemoAuthRoute: typeof DemoAuthRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoErrorBoundaryRoute: typeof DemoErrorBoundaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/error-boundary': {
      id: '/demo/error-boundary'
      path: '/demo/error-boundary'
      fullPath: '/demo/error-boundary'
      preLoaderRoute: typeof DemoErrorBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/auth': {
      id: '/demo/auth'
      path: '/demo/auth'
      fullPath: '/demo/auth'
      preLoaderRoute: typeof DemoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MembersRoute: MembersRoute,
  DemoAuthRoute: DemoAuthRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoErrorBoundaryRoute: DemoErrorBoundaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
