/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoErrorBoundaryRouteImport } from './routes/demo/error-boundary'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DemoAuthRouteImport } from './routes/demo/auth'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedObNoChurchRouteImport } from './routes/_authed/ob/no-church'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoErrorBoundaryRoute = DemoErrorBoundaryRouteImport.update({
  id: '/demo/error-boundary',
  path: '/demo/error-boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAuthRoute = DemoAuthRouteImport.update({
  id: '/demo/auth',
  path: '/demo/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/_authed/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedObNoChurchRoute = AuthedObNoChurchRouteImport.update({
  id: '/_authed/ob/no-church',
  path: '/ob/no-church',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/members': typeof AuthedMembersRoute
  '/demo/auth': typeof DemoAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/error-boundary': typeof DemoErrorBoundaryRoute
  '/ob/no-church': typeof AuthedObNoChurchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/members': typeof AuthedMembersRoute
  '/demo/auth': typeof DemoAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/error-boundary': typeof DemoErrorBoundaryRoute
  '/ob/no-church': typeof AuthedObNoChurchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/demo/auth': typeof DemoAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/error-boundary': typeof DemoErrorBoundaryRoute
  '/_authed/ob/no-church': typeof AuthedObNoChurchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/members'
    | '/demo/auth'
    | '/demo/convex'
    | '/demo/error-boundary'
    | '/ob/no-church'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/members'
    | '/demo/auth'
    | '/demo/convex'
    | '/demo/error-boundary'
    | '/ob/no-church'
  id:
    | '__root__'
    | '/'
    | '/_authed/members'
    | '/demo/auth'
    | '/demo/convex'
    | '/demo/error-boundary'
    | '/_authed/ob/no-church'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  DemoAuthRoute: typeof DemoAuthRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoErrorBoundaryRoute: typeof DemoErrorBoundaryRoute
  AuthedObNoChurchRoute: typeof AuthedObNoChurchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/error-boundary': {
      id: '/demo/error-boundary'
      path: '/demo/error-boundary'
      fullPath: '/demo/error-boundary'
      preLoaderRoute: typeof DemoErrorBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/auth': {
      id: '/demo/auth'
      path: '/demo/auth'
      fullPath: '/demo/auth'
      preLoaderRoute: typeof DemoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/ob/no-church': {
      id: '/_authed/ob/no-church'
      path: '/ob/no-church'
      fullPath: '/ob/no-church'
      preLoaderRoute: typeof AuthedObNoChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  DemoAuthRoute: DemoAuthRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoErrorBoundaryRoute: DemoErrorBoundaryRoute,
  AuthedObNoChurchRoute: AuthedObNoChurchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
